auth_enabled: false

server:
  http_listen_port: 3100

common: #default settings used by loki's components (ingester, querier, distributor, etc.)
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb #(tsdb is the default storage engine 
                  #for Loki, that uses index to store and find chunks)
      object_store: filesystem. #store the data on the local machine's filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: false